### ISSUE TITLE
7-Final touches

### ISSUE THREAD

**Issue by KrystynaMil** [samirm00/duck-duck-clone#18]
- [x] Add media queries
- [x] Validate and fix errors
- [x] Fix bugs 
- [x] Delete unnecessary files

**Comment by samirm00** [comment]
@Houcinos @KrystynaMil @MarieBelyse   I have merged everything together . I have made the pics smaller and font size smaller , I guess it is very good this way . Tomorrow or Friday , we will meet and if we all  like it , I will remove everything from the repo and put only one html and CSS . I will finish the strategy plan , Wireframe . see you on Friday . Kind regards,

**Comment by MarieBelyse** [comment]
Thank you Samir. On 15 Oct 2020 00:26, "Samir M." <notifications@github.com> wrote:
@Houcinos @KrystynaMil @MarieBelyse   I have merged everything together . I have made the pics smaller and font size smaller , I guess it is very good this way . Tomorrow or Friday , we will meet and if we all  like it , I will remove everything from the repo and put only one html and CSS . I will finish the strategy plan , Wireframe . see you on Friday . Kind regards,

**Comment by KrystynaMil** [comment]
@samirm00 Thank you ! Development strategy is really great . But for yours html and css files(search and personal) I don't see any changes. We need to fix it.  . I tried  yesterday but need more time.

**Comment by samirm00** [comment]
@KrystynaMil  I will improve it tonight and we will talk about it on Friday

**Comment by KrystynaMil** [comment]
@samirm00 Super :) See you on Friday !

**Comment by KrystynaMil** [comment]
@samirm00 I changed the personal section and added it to index.html and style.css. So less work for you for tonight;) Only search section to improve . Thank you !

**Comment by samirm00** [comment]
@KrystynaMil  I have already merged everything . Everything is very good , including the personal info and search box

**Comment by samirm00** [comment]
@Houcinos @KrystynaMil @MarieBelyse  I have added the final html and final CSS , they are the merged copy of everything .I sill have to work tonight to improve the search icon , Hover and improve the strategy plan . See you tomorrow and have a nice day

**Comment by samirm00** [comment]
@Houcinos @KrystynaMil @MarieBelyse   Hey , I have added Media queries to the Final .CSS , have you added everything you want to the index.html and style.css  , I will move the added code now  for last time . please  confirm you  are done !

**Comment by MarieBelyse** [comment]
For me yesOn 15 Oct 2020 20:37, "Samir M." <notifications@github.com> wrote:
@Houcinos @KrystynaMil @MarieBelyse   Hey , I have added Media queries to the Final .CSS , have you added everything you want to the index.html and style.css  , I will move the added code now  for last time . please  confirm you  are done !
