### ISSUE TITLE
1- Write the strategy plan

### ISSUE THREAD

**Issue by samirm00** [samirm00/duck-duck-clone#2]
- [x] Write the strategy plan
- [x] Turn the strategy steps to issues 
- [x] Assign each issue to a collaborator
- [x] Add a new  project board `duck-duck-clone-project-board`
- [x] Add the issues to the project board column `To do`, `Doing` , `Ready for review`, `Need revision` and `Done`

**Comment by Houcinos** [comment]
I have noticed that the project can be divided into 5 sections:
1/ 
- Duck logo with DuckDuckGo title
- Search bar with some extension options 
2/ 
- Title and subtitle   
- image
- background
3/ 
- Title and subtitle   
- image
- background
4/
- Title and subtitle   
- image
- background
5/ 
- Title and subtitle   
- image
- button 
- "header"
- background

We can assign one section for each member. For the CSS, we can create a common file. 

Please feel free to put your inputs and later we can agree on one which can fit everyone

**Comment by samirm00** [comment]
The page is already divided into 5 parts , each member can take on part and I will take two parts  and done . for the common CSS file , it will not be possible , better everyone has his/her own , but , we have to agree on everything specially the class names in CSS to avoid any conflicts , that is why I want to start early , so in case of conflicts , we would have more time to do the task .
Best regards ,

**Comment by Houcinos** [comment]
For the CSS, Both solutions are fine for me. Let's agree on this in our meeting tomorrow

**Comment by KrystynaMil** [comment]
I agree with you guys about the parts . About CSS file my opinion that we have to create one file for everyone.I believe it's possible..... Let's talk about all the details on our meeting today :)

**Comment by samirm00** [comment]
@Houcinos @KrystynaMil @MarieBelyse   Please leave a comment or suggestion so I can close the issue !

**Comment by KrystynaMil** [comment]
Everything is alright with the Strategy thank you @samirm00

**Comment by Houcinos** [comment]
From the last meeting I did with Unmesh, the strategy plan should be written in more details. 
We should write down the content of each step: e.g. header, title, subtitle, image. in each of these elements, we need to write some details

**Comment by samirm00** [comment]
@Houcinos   yes , but Stéphane  told me you don't have to be so detailed now .

**Comment by MarieBelyse** [comment]
i agree with everythings
